shmobile: PM: Fix build errors due to missing memlog references
The new merge results in build breakage.

arch/arm/mach-shmobile/clocksuspend.c: In function '__cpg_set_sbsc_freq':
arch/arm/mach-shmobile/clocksuspend.c:1343:3: error: implicit declaration of function 'memory_log_dump_int' [-Werror=implicit-function-declaration]
arch/arm/mach-shmobile/clocksuspend.c:1343:23: error: 'PM_DUMP_ID_ZB3DFS_FREQ' undeclared (first use in this function)
arch/arm/mach-shmobile/clocksuspend.c:1370:3: error: 'PM_DUMP_ID_SET_SBSC_FREQ_ZB3_LOCK' undeclared (first use in this function)
arch/arm/mach-shmobile/clocksuspend.c:1371:3: error: 'PM_DUMP_START' undeclared (first use in this function)

This patch add the missing include for memlog too to fix the build errors.

Signed-off-by: Sriram Venkatakuppaiah <ext-sriram.venkatakuppainah@renesasmobile.com>