regulator: fix compile break due to missing arguments to regulator_register (fixup)
This patch fixes the following compile error:

  CC      drivers/regulator/tps80031-regulator.o
drivers/regulator/tps80031-regulator.c: In function 'tps80031_regulator_probe':
drivers/regulator/tps80031-regulator.c:1047: error: too few arguments to function 'regulator_register'
make[2]: *** [drivers/regulator/tps80031-regulator.o] Error 1

A similar fix can be found at commit 156843470c:

|commit 156843470c4b9ea9698cc245d2cff769b3784088
|Author: Rajendra Nayak <rnayak@ti.com>
|Date:   Thu Nov 24 12:57:17 2011 +0530
|
|    regulator: Fix compile break due to missing arguments to regulator_register
|
|    The commit 2c043bcbf287 ("regulator: pass additional of_node to
|    regulator_register()") caused a compile break because it missed
|    updating the regulator_register() call in gpio-regulator.c with
|    the additional parameter (NULL).
|
|    The compile break as reported by Stephen Rothwell with the
|    x86_64 allmodconfig looked like this
|
|    drivers/regulator/gpio-regulator.c: In function 'gpio_regulator_probe':
|    drivers/regulator/gpio-regulator.c:287:8: error: too few arguments to function 'regulator_register'
|    include/linux/regulator/driver.h:215:23: note: declared here
|
|    Reported-by: Stephen Rothwell <sfr@canb.auug.org.au>
|    Signed-off-by: Rajendra Nayak <rnayak@ti.com>
|    Signed-off-by: Mark Brown <broonie@opensource.wolfsonmicro.com>

Signed-off-by: Shinya Kuribayashi <shinya.kuribayashi.px@renesas.com>